### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ActionBasto** [benoitryder/jmdict-droid#2]
It would be cool to have an option where typing in English characters automatically searched in English and typing in Kanji or Hiragana/Katakana would automatically search in Japanese. This of course would come at the cost of ローマ字 input, which is why it should be optional.

Great app by the way very fast and useful.

**Comment by benoitryder** [comment]
I was thinking of small improvements that should work withoug losing romaji input.
- If input contains Japanese characters, automatically switch to Japanese input.
- If input contains only English characters but there is no results when searching for romaji, switch to English.
- Use a leading `/` to force English search.

The first two points should be enough for most searches, and having to search two times (second point) should not slow down the search significantly.
With this mode the button would switch between "auto mode" (Japanese by default, fallback to English) and "English mode". I think it's better to not have a list with three items (Japanese / English / auto), because having to touch only once is much nicer.

The third point is not very intuitive but allow "advanced users" to never leave the "auto mode".

Would this proposal fit your needs?

(And thanks! I'm glad it's useful!)

**Comment by ActionBasto** [comment]
That sounds like a great solution! Thank you for taking the time to consider my request.

**Comment by benoitryder** [comment]
I implemented the changes. I first thought there was no need to automatically switch to Japanese when using the toggle to explicitely ask for English to Japanese translation, but I changed my mind quickly after pushing the changes (it makes no sense to attempt to use Japanese as English after all). Hence the two new tags.

With the new behavior:
- Japanese input will always search for Japanese.
- Latin input will search for Japanese by default and fallback to English if there was no result.
- The toggle (or a leading `/`) can force *latin* input to search for English instead of Japanese.

Assuming the F-droid build goes smoothly, the new version will be available in a few days.
